### ISSUE TITLE
Add <meta charset> and <meta name, content> tags for better responsive web design?

### ISSUE THREAD

**Issue by CoolDeveloper101** [alephjs/alephjs-templates#2]
It seems like good practice to include these meta tags at the beginning of the web page -
```html
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```
Should they also be added to the hello-world template?

**Comment by ije** [comment]
@CoolDeveloper101 alephjs will create `<meta charset="UTF-8" />` automatically, `viewport` you are right! can you please make a PR? or i will do it later, thanks

**Comment by CoolDeveloper101** [comment]
I will make a PR soon.
